const INTERNALSERVERERROR = 500;
const BADREQUEST = 400;
const UNAUTHORIZED = 401;
const FORBIDDEN = 403;
const PAGENOTFOUND = 404;
const HTTP200OK = 200;

module.exports = {
  INTERNALSERVERERROR: INTERNALSERVERERROR,
  BADREQUEST: BADREQUEST,
  HTTP200OK: HTTP200OK,
  PAGENOTFOUND: PAGENOTFOUND,
  UNAUTHORIZED: UNAUTHORIZED,
  FORBIDDEN: FORBIDDEN,
};
